---
generic-service:
  replicaCount: 2
  resources:
    limits:
      memory: "2Gi"
      cpu: "1000m"
    requests:
      memory: "125Mi"
      cpu: "15m"

  ingress:
    hosts:
      - prisonvisits.service.gov.uk
      - www.prisonvisits.service.gov.uk

  scheduledDowntime:
    enabled: true

  namespace_secrets:
    elasticache-prison-visits-booking-token-cache-production:
      REDIS_URL: url

  env:
    NOMIS_STAFF_SLOT_AVAILABILITY_ENABLED: "true"
    NOMIS_OAUTH_HOST: "https://sign-in.hmpps.service.justice.gov.uk"
    PRISON_API_HOST: "https://prison-api.prison.service.justice.gov.uk"
    PRISON_VISITS_API: "https://staff.prisonvisits.prison.service.justice.gov.uk/"
    PUBLIC_SERVICE_URL: "https://prisonvisits.service.gov.uk"
    RACK_ENV: "production"
    RAILS_ENV: "production"
    RAILS_SERVE_STATIC_FILES: "true"
    EMAIL_DOMAIN: "email.prisonvisits.service.gov.uk"
    SENTRY_CURRENT_ENV: "production"
    SERVICE_URL: "https://prison-visits-public-production.apps.live.cloud-platform.service.justice.gov.uk"
    STAFF_SERVICE_URL: "https://staff.prisonvisits.prison.service.justice.gov.uk"
    VSIP_HOST: "https://hmpps-manage-prison-visits-orchestration.prison.service.justice.gov.uk"
    PUBLIC_PRISONS_WITH_SLOT_AVAILABILITY: >
      High Down,
    STAFF_PRISONS_WITH_SLOT_AVAILABILITY: >
      High Down,
    ENVIRONMENT_NAME: prod
